version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 74apache
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
    networks:
      - web_dev

  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bace
      MYSQL_DATABASE: bace
      MYSQL_USER: root
      MYSQL_PASSWORD: bace
    ports:
      - 6033:3306
    networks:
      - web_dev
networks:
  web_dev:
    driver: bridge
